CREATE SEQUENCE SECTOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SECTOR (
    ID INTEGER DEFAULT SECTOR_SEQ.nextval NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CONSUMPTION_LIMIT NUMBER(10, 2) NOT NULL
    USER_ID NUMBER NOT NULL,
    CONSTRAINT PK_TBL_SECTOR PRIMARY KEY (ID),
    CONSTRAINT FK_TBL_SECTOR_USER FOREIGN KEY (USER_ID) REFERENCES TBL_USER(ID)
)